#ifndef DECLARATIONS_H
#define DECLARATIONS_H

#define MAP_EMPTY 0
#define MAP_WALL 1

#define MOVE_LEFT 50
#define MOVE_RIGHT 51
#define MOVE_UP 52
#define MOVE_DOWN 53

#define BOARD_CANT_MOVE 54
#define BOARD_CAN_MOVE 55

#define CHAR_ISENEMY 56
#define CHAR_ISFRIENDLY 57

#define MOVE_AUTHORIZED 58
#define MOVE_ERROR_OUTOFBOUNDS 59
#define MOVE_ERROR_BLOCKED 60
#define MOVE_ERROR_UNKNOWN 61

#define CHARACTER_BOSS 90
#define CHARACTER_ENEMY 91
#define CHARACTER_ITEM 92
#define CHARACTER_SPAWN 98
#define CHARACTER_EXIT 99

#endif // DECLARATIONS_H
